spring:
  application:
    name: file-generator
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.bvv.filegeneration: DEBUG

